#!/usr/bin/env bash
# comment
echo $$ >> /var/run/myscript.pid
trap "echo 'Y U no love me?!'" SIGINT
trap "echo 'I hate the kill command' && rm -f /var/run/myscript.pid && exit" SIGTERM SIGQUIT
while true
do
	echo 'To infinity and beyond'
	sleep 2
done
